using RegProbe.Application.Services;
using RegProbe.Engine.Tweaks;

namespace RegProbe.Tests;

public sealed class ResearchAppSurfaceCatalogTests
{
    [Fact]
    public void Catalog_Surfaces_Validated_Research_Cards_From_App_Surface_Manifest()
    {
        var catalog = new TweakCatalogService();

        var beepTweak = catalog.FindById("audio.disable-beep");
        var blockMicrosoftAccountsTweak = catalog.FindById("privacy.block-microsoft-accounts");
        var biometricsDomainLogonTweak = catalog.FindById("privacy.disable-biometrics-domain-logon");
        var biometricsLogonTweak = catalog.FindById("privacy.disable-biometrics-logon");
        var biometricsTweak = catalog.FindById("privacy.disable-biometrics");
        var cameraTweak = catalog.FindById("privacy.disable-camera");
        var consumerAccountContentTweak = catalog.FindById("privacy.disable-consumer-account-content");
        var developerModeTweak = catalog.FindById("developer.windows-dev-mode");
        var disableAdvertisingIdTweak = catalog.FindById("privacy.disable-advertising-id");
        var dotnetTelemetryTweak = catalog.FindById("developer.dotnet-telemetry-disable");
        var disableAppDiagnosticsTweak = catalog.FindById("privacy.disable-app-diagnostics");
        var disableAppLaunchTrackingTweak = catalog.FindById("privacy.disable-app-launch-tracking");
        var disableAppSuggestionsTweak = catalog.FindById("privacy.disable-app-suggestions");
        var disableApplicationTelemetryTweak = catalog.FindById("privacy.disable-application-telemetry");
        var disableBackgroundAppsTweak = catalog.FindById("privacy.disable-background-apps");
        var disableCopilotTweak = catalog.FindById("privacy.disable-copilot");
        var disableCrossDeviceExperiencesPolicyTweak = catalog.FindById("privacy.disable-cross-device-experiences.policy");
        var disableDeviceNameTelemetryTweak = catalog.FindById("privacy.disable-device-name-telemetry");
        var disableDiagnosticDataDeleteTweak = catalog.FindById("privacy.disable-diagnostic-data-delete");
        var disableDiagnosticDataViewerTweak = catalog.FindById("privacy.disable-diagnostic-data-viewer");
        var disableFeedbackNotificationsTweak = catalog.FindById("privacy.disable-feedback-notifications");
        var disableFindMyDeviceTweak = catalog.FindById("privacy.disable-find-my-device");
        var disableFontProvidersTweak = catalog.FindById("privacy.disable-font-providers");
        var fullPathTweak = catalog.FindById("explorer.show-full-path");
        var policyTweak = catalog.FindById("policy.system.enable-virtualization");
        var disconnectedAudioTweak = catalog.FindById("audio.show-disconnected-devices");
        var hiddenAudioTweak = catalog.FindById("audio.show-hidden-devices");
        var compactModeTweak = catalog.FindById("explorer.enable-explorer-compact-mode");
        var compressedColorTweak = catalog.FindById("explorer.show-compressed-and-encrypted-files-in-color");
        var disableChatTweak = catalog.FindById("explorer.disable-taskbar-chat");
        var disableLowDiskSpaceWarningTweak = catalog.FindById("explorer.disable-low-disk-space-warning");
        var disableActiveProbingTweak = catalog.FindById("network.disable-active-probing");
        var disableFeedbackFrequencyTweak = catalog.FindById("notifications.disable-feedback-frequency");
        var disableIpv6Tweak = catalog.FindById("network.disable-ipv6");
        var disableLockScreenTweak = catalog.FindById("notifications.disable-lock-screen");
        var disableLlmnrTweak = catalog.FindById("network.disable-llmnr");
        var enableLltdIoTweak = catalog.FindById("network.enable-lltdio");
        var disableLocalSecurityQuestionsTweak = catalog.FindById("privacy.disable-local-security-questions");
        var disableLocationScriptingTweak = catalog.FindById("privacy.disable-location-scripting");
        var disableLocationServicesTweak = catalog.FindById("privacy.disable-location-services");
        var disableMdmEnrollmentTweak = catalog.FindById("privacy.disable-mdm-enrollment");
        var disableMdnsTweak = catalog.FindById("network.disable-mdns");
        var disableMessageSyncTweak = catalog.FindById("privacy.disable-message-sync");
        var disablePlaintextSmbPasswordsTweak = catalog.FindById("network.disable-plaintext-smb-passwords");
        var disableFileHistoryTweak = catalog.FindById("privacy.disable-file-history");
        var disableLanguageListAccessTweak = catalog.FindById("privacy.disable-language-list-access");
        var disableLocationConsentSystemTweak = catalog.FindById("privacy.disable-location-consent-system");
        var disableOneSettingsDownloadsTweak = catalog.FindById("privacy.disable-onesettings-downloads");
        var disableOnlineTipsTweak = catalog.FindById("privacy.disable-online-tips");
        var disablePcaDiagnosticsPolicyTweak = catalog.FindById("privacy.disable-pca-diagnostics.policy");
        var disableProgramCompatibilityAssistantTweak = catalog.FindById("privacy.disable-program-compatibility-assistant");
        var disablePhoneLinkingTweak = catalog.FindById("privacy.disable-phone-linking");
        var disableRecallTweak = catalog.FindById("privacy.disable-recall");
        var disableResumeTweak = catalog.FindById("privacy.disable-resume");
        var disableRsopLoggingTweak = catalog.FindById("privacy.disable-rsop-logging");
        var disableSearchBoxSuggestionsTweak = catalog.FindById("privacy.disable-search-box-suggestions");
        var disableSearchHistoryTweak = catalog.FindById("privacy.disable-search-history");
        var disableSensorsTweak = catalog.FindById("privacy.disable-sensors");
        var disableSmb1Tweak = catalog.FindById("network.disable-smb1");
        var disableSmb2Tweak = catalog.FindById("network.disable-smb2");
        var disableStepsRecorderTweak = catalog.FindById("privacy.disable-steps-recorder");
        var disableWifiSenseTweak = catalog.FindById("network.disable-wifi-sense");
        var disableWindowsLocationProviderTweak = catalog.FindById("privacy.disable-windows-location-provider");
        var enableLltdResponderTweak = catalog.FindById("network.enable-lltd-responder");
        var disableMirroringTweak = catalog.FindById("notifications.disable-mirroring");
        var disableNetbiosResolutionTweak = catalog.FindById("network.disable-netbios-resolution");
        var requireNtlmSspClientSessionSecurityTweak = catalog.FindById("network.require-ntlm-ssp-client-session-security");
        var smbEnableLargeMtuTweak = catalog.FindById("network.smb-enable-large-mtu");
        var smbEncryptDataTweak = catalog.FindById("network.smb-encrypt-data");
        var smbRejectUnencryptedAccessTweak = catalog.FindById("network.smb-reject-unencrypted-access");
        var disableSmartNameResolutionTweak = catalog.FindById("network.disable-smart-name-resolution");
        var disableTelemetryChangeNotificationsTweak = catalog.FindById("privacy.disable-telemetry-change-notifications");
        var disableTelemetryOptInUiTweak = catalog.FindById("privacy.disable-telemetry-optin-ui");
        var disableTileTweak = catalog.FindById("notifications.disable-tile");
        var disableToastTweak = catalog.FindById("notifications.disable-toast");
        var disableSwitchbackPolicyTweak = catalog.FindById("privacy.disable-switchback.policy");
        var hideLastLoggedInUserTweak = catalog.FindById("privacy.hide-last-logged-in-user");
        var hideRecommendedPersonalizedSitesPolicyTweak = catalog.FindById("privacy.hide-recommended-personalized-sites");
        var hideRecommendedPersonalizedSitesUserTweak = catalog.FindById("privacy.hide-recommended-personalized-sites-user");
        var hideRecommendedSectionPolicyTweak = catalog.FindById("privacy.hide-recommended-section");
        var hideRecommendedSectionUserTweak = catalog.FindById("privacy.hide-recommended-section-user");
        var hideUsernameAtSigninTweak = catalog.FindById("privacy.hide-username-at-signin");
        var limitDiagnosticLogCollectionTweak = catalog.FindById("privacy.limit-diagnostic-log-collection");
        var limitDumpCollectionTweak = catalog.FindById("privacy.limit-dump-collection");
        var troubleshooterDontRunTweak = catalog.FindById("privacy.troubleshooter-dont-run");
        var disableWindowsTipsTweak = catalog.FindById("privacy.disable-windows-tips");
        var driveLettersTweak = catalog.FindById("explorer.show-drive-letters-first");
        var infoTipsTweak = catalog.FindById("explorer.show-info-tips");
        var launchSeparateProcessTweak = catalog.FindById("explorer.launch-folder-windows-in-a-separate-process");
        var longPathsTweak = catalog.FindById("developer.enable-windows-long-paths");
        var hiddenFilesTweak = catalog.FindById("explorer.show-hidden-files");
        var fileExtensionsTweak = catalog.FindById("explorer.show-file-extensions");
        var preferIpv4Tweak = catalog.FindById("network.prefer-ipv4");
        var powershellExecutionTweak = catalog.FindById("developer.powershell-execution");
        var pythonPathFixTweak = catalog.FindById("developer.python-path-fix");
        var showProtectedFilesTweak = catalog.FindById("explorer.show-protected-operating-system-files");
        var statusBarTweak = catalog.FindById("explorer.show-status-bar");
        var taskbarAlignmentTweak = catalog.FindById("explorer.taskbar-alignment-left");
        var typeOverlayTweak = catalog.FindById("explorer.show-type-overlay");
        var powerTweak = catalog.FindById("power.control.class1-initial-unpark-count");
        var watchdogTweak = catalog.FindById("power.session-watchdog-timeouts");
        var subtreeTweak = catalog.FindById("power.control.power-request-override-subtree");
        var executiveTweak = catalog.FindById("system.executive-additional-worker-threads");
        var kernelTweak = catalog.FindById("system.kernel.disable-exception-chain-validation");
        var bsodAutoRebootTweak = catalog.FindById("system.bsod-disable-auto-reboot");
        var bsodDisplayParametersTweak = catalog.FindById("system.bsod-display-parameters");
        var disableFullscreenOptimizationsTweak = catalog.FindById("system.disable-fullscreen-optimizations");
        var disableGameRecordingBroadcastingTweak = catalog.FindById("system.disable-game-recording-broadcasting");
        var disableSearchRemoteQueriesTweak = catalog.FindById("system.disable-search-remote-queries");
        var disableSearchWebResultsTweak = catalog.FindById("system.disable-search-web-results");
        var enableIndexingEncryptedItemsTweak = catalog.FindById("system.enable-indexing-encrypted-items");
        var graphicsTdrDdiDelayTweak = catalog.FindById("system.graphics-tdr-ddi-delay");
        var graphicsTdrDelayTweak = catalog.FindById("system.graphics-tdr-delay");
        var graphicsTdrLevelTweak = catalog.FindById("system.graphics-tdr-level");
        var dwmDisableOverlayMinFpsTweak = catalog.FindById("system.dwm-disable-overlay-min-fps");
        var graphicsTdrLimitCountTweak = catalog.FindById("system.graphics-tdr-limit-count");
        var graphicsTdrLimitTimeTweak = catalog.FindById("system.graphics-tdr-limit-time");
        var kernelThreadDpcEnableTweak = catalog.FindById("system.kernel-thread-dpc-enable");
        var memoryClearPagefileAtShutdownTweak = catalog.FindById("system.memory-clear-pagefile-at-shutdown");
        var memoryDisablePagingExecutiveTweak = catalog.FindById("system.memory-disable-paging-executive");
        var memoryLargeSystemCacheClientTweak = catalog.FindById("system.memory-large-system-cache-client");
        var memoryNonpagedPoolDynamicTweak = catalog.FindById("system.memory-nonpaged-pool-dynamic");
        var memoryPagedPoolDynamicTweak = catalog.FindById("system.memory-paged-pool-dynamic");
        var memoryRegistryQuotaDefaultTweak = catalog.FindById("system.memory-registry-quota-default");
        var ntfsDisable8dot3Tweak = catalog.FindById("system.ntfs-disable-8dot3");
        var ntfsDisableLastAccessTweak = catalog.FindById("system.ntfs-disable-last-access");
        var ntfsEnableLongPathsTweak = catalog.FindById("system.ntfs-enable-long-paths");
        var ntfsResetMemoryUsageTweak = catalog.FindById("system.ntfs-reset-memory-usage");
        var ntfsResetMftZoneTweak = catalog.FindById("system.ntfs-reset-mft-zone");
        var waitToKillServiceTimeoutTweak = catalog.FindById("system.wait-to-kill-service-timeout");
        var priorityControlTweak = catalog.FindById("system.priority-control");
        var reliabilityTimestampEnabledTweak = catalog.FindById("system.reliability-timestamp-enabled");
        var disableAnimationsTweak = catalog.FindById("performance.disable-animations");
        var disableMenuShowDelayTweak = catalog.FindById("performance.disable-menu-show-delay");
        var disableAcrylicLogonTweak = catalog.FindById("visibility.disable-acrylic-logon");
        var disableCommonControlAnimationsTweak = catalog.FindById("visibility.disable-common-control-animations");
        var disableFirstSigninAnimationTweak = catalog.FindById("visibility.disable-first-signin-animation");
        var disableLockScreenCameraTweak = catalog.FindById("visibility.disable-lock-screen-camera");
        var disableLockScreenChangesTweak = catalog.FindById("visibility.disable-lock-screen-changes");
        var disableAppArchivingTweak = catalog.FindById("system.disable-app-archiving");
        var disableAutoMaintenanceTweak = catalog.FindById("system.disable-auto-maintenance");
        var disableBackgroundGpUpdatesTweak = catalog.FindById("system.disable-background-gp-updates");
        var disableClipboardHistoryTweak = catalog.FindById("system.disable-clipboard-history");
        var disableClipboardRedirectionTweak = catalog.FindById("system.disable-clipboard-redirection");
        var aeroShakeTweak = catalog.FindById("system.aero-shake");
        var disableJpegReductionTweak = catalog.FindById("system.disable-jpeg-reduction");
        var disableSearchHighlightsPolicyTweak = catalog.FindById("system.disable-search-highlights-policy");
        var disableStartupDelayTweak = catalog.FindById("system.disable-startup-delay");
        var enableGameModeTweak = catalog.FindById("system.enable-game-mode");

        Assert.NotNull(beepTweak);
        Assert.NotNull(blockMicrosoftAccountsTweak);
        Assert.NotNull(biometricsDomainLogonTweak);
        Assert.NotNull(biometricsLogonTweak);
        Assert.NotNull(biometricsTweak);
        Assert.NotNull(cameraTweak);
        Assert.NotNull(consumerAccountContentTweak);
        Assert.NotNull(developerModeTweak);
        Assert.NotNull(disableAdvertisingIdTweak);
        Assert.NotNull(dotnetTelemetryTweak);
        Assert.NotNull(disableAppDiagnosticsTweak);
        Assert.NotNull(disableAppLaunchTrackingTweak);
        Assert.NotNull(disableAppSuggestionsTweak);
        Assert.NotNull(disableApplicationTelemetryTweak);
        Assert.NotNull(disableBackgroundAppsTweak);
        Assert.NotNull(disableCopilotTweak);
        Assert.NotNull(disableCrossDeviceExperiencesPolicyTweak);
        Assert.NotNull(disableDeviceNameTelemetryTweak);
        Assert.NotNull(disableDiagnosticDataDeleteTweak);
        Assert.NotNull(disableDiagnosticDataViewerTweak);
        Assert.NotNull(disableFeedbackNotificationsTweak);
        Assert.NotNull(disableFindMyDeviceTweak);
        Assert.NotNull(disableFontProvidersTweak);
        Assert.NotNull(fullPathTweak);
        Assert.NotNull(hiddenAudioTweak);
        Assert.NotNull(disconnectedAudioTweak);
        Assert.NotNull(compactModeTweak);
        Assert.NotNull(compressedColorTweak);
        Assert.NotNull(disableChatTweak);
        Assert.NotNull(disableLowDiskSpaceWarningTweak);
        Assert.NotNull(disableActiveProbingTweak);
        Assert.NotNull(disableFeedbackFrequencyTweak);
        Assert.NotNull(disableIpv6Tweak);
        Assert.NotNull(disableLockScreenTweak);
        Assert.NotNull(disableLlmnrTweak);
        Assert.NotNull(enableLltdIoTweak);
        Assert.NotNull(disableLocalSecurityQuestionsTweak);
        Assert.NotNull(disableLocationScriptingTweak);
        Assert.NotNull(disableLocationServicesTweak);
        Assert.NotNull(disableMdmEnrollmentTweak);
        Assert.NotNull(disableMdnsTweak);
        Assert.NotNull(disableMessageSyncTweak);
        Assert.NotNull(disablePlaintextSmbPasswordsTweak);
        Assert.NotNull(disableFileHistoryTweak);
        Assert.NotNull(disableLanguageListAccessTweak);
        Assert.NotNull(disableLocationConsentSystemTweak);
        Assert.NotNull(disableOneSettingsDownloadsTweak);
        Assert.NotNull(disableOnlineTipsTweak);
        Assert.NotNull(disablePcaDiagnosticsPolicyTweak);
        Assert.NotNull(disableProgramCompatibilityAssistantTweak);
        Assert.NotNull(disablePhoneLinkingTweak);
        Assert.NotNull(disableRecallTweak);
        Assert.NotNull(disableResumeTweak);
        Assert.NotNull(disableRsopLoggingTweak);
        Assert.NotNull(disableSearchBoxSuggestionsTweak);
        Assert.NotNull(disableSearchHistoryTweak);
        Assert.NotNull(disableSensorsTweak);
        Assert.NotNull(disableSmb1Tweak);
        Assert.NotNull(disableSmb2Tweak);
        Assert.NotNull(disableStepsRecorderTweak);
        Assert.NotNull(disableWifiSenseTweak);
        Assert.NotNull(disableWindowsLocationProviderTweak);
        Assert.NotNull(enableLltdResponderTweak);
        Assert.NotNull(disableMirroringTweak);
        Assert.NotNull(disableNetbiosResolutionTweak);
        Assert.NotNull(requireNtlmSspClientSessionSecurityTweak);
        Assert.NotNull(smbEnableLargeMtuTweak);
        Assert.NotNull(smbEncryptDataTweak);
        Assert.NotNull(smbRejectUnencryptedAccessTweak);
        Assert.NotNull(disableSmartNameResolutionTweak);
        Assert.NotNull(disableTelemetryChangeNotificationsTweak);
        Assert.NotNull(disableTelemetryOptInUiTweak);
        Assert.NotNull(disableTileTweak);
        Assert.NotNull(disableToastTweak);
        Assert.NotNull(disableSwitchbackPolicyTweak);
        Assert.NotNull(hideLastLoggedInUserTweak);
        Assert.NotNull(hideRecommendedPersonalizedSitesPolicyTweak);
        Assert.NotNull(hideRecommendedPersonalizedSitesUserTweak);
        Assert.NotNull(hideRecommendedSectionPolicyTweak);
        Assert.NotNull(hideRecommendedSectionUserTweak);
        Assert.NotNull(hideUsernameAtSigninTweak);
        Assert.NotNull(limitDiagnosticLogCollectionTweak);
        Assert.NotNull(limitDumpCollectionTweak);
        Assert.NotNull(troubleshooterDontRunTweak);
        Assert.NotNull(disableWindowsTipsTweak);
        Assert.NotNull(driveLettersTweak);
        Assert.NotNull(hiddenFilesTweak);
        Assert.NotNull(fileExtensionsTweak);
        Assert.NotNull(infoTipsTweak);
        Assert.NotNull(launchSeparateProcessTweak);
        Assert.NotNull(longPathsTweak);
        Assert.NotNull(policyTweak);
        Assert.NotNull(preferIpv4Tweak);
        Assert.NotNull(powershellExecutionTweak);
        Assert.NotNull(pythonPathFixTweak);
        Assert.NotNull(showProtectedFilesTweak);
        Assert.NotNull(powerTweak);
        Assert.NotNull(statusBarTweak);
        Assert.NotNull(taskbarAlignmentTweak);
        Assert.NotNull(watchdogTweak);
        Assert.NotNull(subtreeTweak);
        Assert.NotNull(executiveTweak);
        Assert.NotNull(kernelTweak);
        Assert.NotNull(bsodAutoRebootTweak);
        Assert.NotNull(bsodDisplayParametersTweak);
        Assert.NotNull(disableFullscreenOptimizationsTweak);
        Assert.NotNull(disableGameRecordingBroadcastingTweak);
        Assert.NotNull(disableSearchRemoteQueriesTweak);
        Assert.NotNull(disableSearchWebResultsTweak);
        Assert.NotNull(enableIndexingEncryptedItemsTweak);
        Assert.NotNull(graphicsTdrDdiDelayTweak);
        Assert.NotNull(graphicsTdrDelayTweak);
        Assert.NotNull(graphicsTdrLevelTweak);
        Assert.NotNull(dwmDisableOverlayMinFpsTweak);
        Assert.NotNull(graphicsTdrLimitCountTweak);
        Assert.NotNull(graphicsTdrLimitTimeTweak);
        Assert.NotNull(kernelThreadDpcEnableTweak);
        Assert.NotNull(memoryClearPagefileAtShutdownTweak);
        Assert.NotNull(memoryDisablePagingExecutiveTweak);
        Assert.NotNull(memoryLargeSystemCacheClientTweak);
        Assert.NotNull(memoryNonpagedPoolDynamicTweak);
        Assert.NotNull(memoryPagedPoolDynamicTweak);
        Assert.NotNull(memoryRegistryQuotaDefaultTweak);
        Assert.NotNull(ntfsDisable8dot3Tweak);
        Assert.NotNull(ntfsDisableLastAccessTweak);
        Assert.NotNull(ntfsEnableLongPathsTweak);
        Assert.NotNull(ntfsResetMemoryUsageTweak);
        Assert.NotNull(ntfsResetMftZoneTweak);
        Assert.NotNull(waitToKillServiceTimeoutTweak);
        Assert.NotNull(priorityControlTweak);
        Assert.NotNull(reliabilityTimestampEnabledTweak);
        Assert.NotNull(disableAnimationsTweak);
        Assert.NotNull(disableMenuShowDelayTweak);
        Assert.NotNull(disableAcrylicLogonTweak);
        Assert.NotNull(disableCommonControlAnimationsTweak);
        Assert.NotNull(disableFirstSigninAnimationTweak);
        Assert.NotNull(disableLockScreenCameraTweak);
        Assert.NotNull(disableLockScreenChangesTweak);
        Assert.NotNull(disableAppArchivingTweak);
        Assert.NotNull(disableAutoMaintenanceTweak);
        Assert.NotNull(disableBackgroundGpUpdatesTweak);
        Assert.NotNull(disableClipboardHistoryTweak);
        Assert.NotNull(disableClipboardRedirectionTweak);
        Assert.NotNull(aeroShakeTweak);
        Assert.NotNull(disableJpegReductionTweak);
        Assert.NotNull(disableSearchHighlightsPolicyTweak);
        Assert.NotNull(disableStartupDelayTweak);
        Assert.NotNull(enableGameModeTweak);
        Assert.NotNull(typeOverlayTweak);
        Assert.Equal("System Beep Driver", beepTweak!.Name);
        Assert.Equal("Microsoft Accounts on This Device", blockMicrosoftAccountsTweak!.Name);
        Assert.Equal("Biometric Sign-in for Domain Accounts", biometricsDomainLogonTweak!.Name);
        Assert.Equal("Biometric Sign-in", biometricsLogonTweak!.Name);
        Assert.Equal("Windows Biometrics", biometricsTweak!.Name);
        Assert.Equal("Camera Device Use", cameraTweak!.Name);
        Assert.Equal("Cloud Consumer Account State Content", consumerAccountContentTweak!.Name);
        Assert.Equal("Windows Developer Mode", developerModeTweak!.Name);
        Assert.Equal("Disable Advertising ID", disableAdvertisingIdTweak!.Name);
        Assert.Equal(".NET CLI Telemetry Opt-Out", dotnetTelemetryTweak!.Name);
        Assert.Equal("App Diagnostic Information Access", disableAppDiagnosticsTweak!.Name);
        Assert.Equal("App Launch Tracking", disableAppLaunchTrackingTweak!.Name);
        Assert.Equal("App Suggestions in Start", disableAppSuggestionsTweak!.Name);
        Assert.Equal("Disable Application Telemetry", disableApplicationTelemetryTweak!.Name);
        Assert.Equal("Background App Execution", disableBackgroundAppsTweak!.Name);
        Assert.Equal("Windows Copilot", disableCopilotTweak!.Name);
        Assert.Equal("Cross-Device Experiences Machine Policy", disableCrossDeviceExperiencesPolicyTweak!.Name);
        Assert.Equal("Device Name in Diagnostic Data", disableDeviceNameTelemetryTweak!.Name);
        Assert.Equal("Diagnostic Data Deletion", disableDiagnosticDataDeleteTweak!.Name);
        Assert.Equal("Diagnostic Data Viewer", disableDiagnosticDataViewerTweak!.Name);
        Assert.Equal("Microsoft Feedback Notifications", disableFeedbackNotificationsTweak!.Name);
        Assert.Equal("Find My Device", disableFindMyDeviceTweak!.Name);
        Assert.Equal("Online Font Providers", disableFontProvidersTweak!.Name);
        Assert.Equal("Show Full Path in Explorer", fullPathTweak!.Name);
        Assert.Equal("Show Hidden Audio Devices", hiddenAudioTweak!.Name);
        Assert.Equal("Show Disconnected Audio Devices", disconnectedAudioTweak!.Name);
        Assert.Equal("Enable Explorer Compact View", compactModeTweak!.Name);
        Assert.Equal("Show Compressed and Encrypted Files in Color", compressedColorTweak!.Name);
        Assert.Equal("Taskbar Chat Icon", disableChatTweak!.Name);
        Assert.Equal("Low Disk Space Warning", disableLowDiskSpaceWarningTweak!.Name);
        Assert.Equal("NCSI Active Probing Policy", disableActiveProbingTweak!.Name);
        Assert.Equal("Windows Feedback Request Frequency", disableFeedbackFrequencyTweak!.Name);
        Assert.Equal("IPv6 Stack Disable Override", disableIpv6Tweak!.Name);
        Assert.Equal("Lock Screen Toast Notifications", disableLockScreenTweak!.Name);
        Assert.Equal("Link-Local Multicast Name Resolution (LLMNR)", disableLlmnrTweak!.Name);
        Assert.Equal("LLTD Mapper I/O Driver Policy", enableLltdIoTweak!.Name);
        Assert.Equal("Security Questions for Local Accounts", disableLocalSecurityQuestionsTweak!.Name);
        Assert.Equal("Location Scripting", disableLocationScriptingTweak!.Name);
        Assert.Equal("Location Feature", disableLocationServicesTweak!.Name);
        Assert.Equal("MDM Enrollment", disableMdmEnrollmentTweak!.Name);
        Assert.Equal("Set mDNS Policy to Local Settings", disableMdnsTweak!.Name);
        Assert.Equal("Message Service Cloud Sync", disableMessageSyncTweak!.Name);
        Assert.Equal("Plaintext SMB Passwords", disablePlaintextSmbPasswordsTweak!.Name);
        Assert.Equal("File History", disableFileHistoryTweak!.Name);
        Assert.Equal("Website Access to Language List", disableLanguageListAccessTweak!.Name);
        Assert.Equal("Location Consent Store (System)", disableLocationConsentSystemTweak!.Name);
        Assert.Equal("OneSettings Downloads", disableOneSettingsDownloadsTweak!.Name);
        Assert.Equal("Online Tips in Settings", disableOnlineTipsTweak!.Name);
        Assert.Equal("Disable PCA Compatibility Diagnostics Detection", disablePcaDiagnosticsPolicyTweak!.Name);
        Assert.Equal("Disable Program Compatibility Assistant", disableProgramCompatibilityAssistantTweak!.Name);
        Assert.Equal("Phone-PC Linking", disablePhoneLinkingTweak!.Name);
        Assert.Equal("Recall Snapshot Saving", disableRecallTweak!.Name);
        Assert.Equal("Disable Resume for Current User", disableResumeTweak!.Name);
        Assert.Equal("Resultant Set of Policy Logging", disableRsopLoggingTweak!.Name);
        Assert.Equal("File Explorer Search Box Suggestions", disableSearchBoxSuggestionsTweak!.Name);
        Assert.Equal("Search History Storage and Display", disableSearchHistoryTweak!.Name);
        Assert.Equal("Windows Sensors", disableSensorsTweak!.Name);
        Assert.Equal("SMBv1 Server Protocol Support", disableSmb1Tweak!.Name);
        Assert.Equal("SMBv2 and SMBv3 Server Protocol Support", disableSmb2Tweak!.Name);
        Assert.Equal("Steps Recorder", disableStepsRecorderTweak!.Name);
        Assert.Equal("Wi-Fi Sense Suggested Hotspot Policy", disableWifiSenseTweak!.Name);
        Assert.Equal("Windows Location Provider", disableWindowsLocationProviderTweak!.Name);
        Assert.Equal("LLTD Responder Driver Policy", enableLltdResponderTweak!.Name);
        Assert.Equal("Notification Mirroring", disableMirroringTweak!.Name);
        Assert.Equal("DNS Client NetBIOS Name Resolution", disableNetbiosResolutionTweak!.Name);
        Assert.Equal("Require NTLM SSP Client Session Security and 128-bit Encryption", requireNtlmSspClientSessionSecurityTweak!.Name);
        Assert.Equal("SMB Client Large MTU", smbEnableLargeMtuTweak!.Name);
        Assert.Equal("SMB Server Encryption Requirement", smbEncryptDataTweak!.Name);
        Assert.Equal("SMB Server Reject Unencrypted Access", smbRejectUnencryptedAccessTweak!.Name);
        Assert.Equal("Smart Multi-Homed Name Resolution", disableSmartNameResolutionTweak!.Name);
        Assert.Equal("Diagnostic Data Change Notifications", disableTelemetryChangeNotificationsTweak!.Name);
        Assert.Equal("Diagnostic Data Opt-In Settings UI", disableTelemetryOptInUiTweak!.Name);
        Assert.Equal("Tile Notifications", disableTileTweak!.Name);
        Assert.Equal("Toast Notifications", disableToastTweak!.Name);
        Assert.Equal("Disable SwitchBack Compatibility Policy", disableSwitchbackPolicyTweak!.Name);
        Assert.Equal("Display of the Last Signed-In Username", hideLastLoggedInUserTweak!.Name);
        Assert.Equal("Start Personalized Site Recommendations", hideRecommendedPersonalizedSitesPolicyTweak!.Name);
        Assert.Equal("Start Personalized Site Recommendations (Current User)", hideRecommendedPersonalizedSitesUserTweak!.Name);
        Assert.Equal("Start Menu Recommended Section", hideRecommendedSectionPolicyTweak!.Name);
        Assert.Equal("Start Menu Recommended Section (Current User)", hideRecommendedSectionUserTweak!.Name);
        Assert.Equal("Display of Username During Sign-In", hideUsernameAtSigninTweak!.Name);
        Assert.Equal("Advanced Diagnostic Log Collection", limitDiagnosticLogCollectionTweak!.Name);
        Assert.Equal("Diagnostic Dump Collection", limitDumpCollectionTweak!.Name);
        Assert.Equal("Recommended Troubleshooting for Known Problems", troubleshooterDontRunTweak!.Name);
        Assert.Equal("Turn Off Windows Tips", disableWindowsTipsTweak!.Name);
        Assert.Equal("Show Drive Letters First", driveLettersTweak!.Name);
        Assert.Equal("Show Hidden Files and Folders", hiddenFilesTweak!.Name);
        Assert.Equal("Show File Extensions", fileExtensionsTweak!.Name);
        Assert.Equal("Show Explorer Info Tips", infoTipsTweak!.Name);
        Assert.Equal("Launch Folder Windows in a Separate Process", launchSeparateProcessTweak!.Name);
        Assert.Equal("Windows Long Paths", longPathsTweak!.Name);
        Assert.Equal("Enable Virtualization", policyTweak!.Name);
        Assert.Equal("IPv4 Preference Override", preferIpv4Tweak!.Name);
        Assert.Equal("PowerShell Script Execution Policy", powershellExecutionTweak!.Name);
        Assert.Equal("Enable Windows Long Paths for Python Workflows", pythonPathFixTweak!.Name);
        Assert.Equal("Show Protected Operating System Files", showProtectedFilesTweak!.Name);
        Assert.Equal("Class1 Initial Unpark Count", powerTweak!.Name);
        Assert.Equal("Show Status Bar", statusBarTweak!.Name);
        Assert.Equal("Taskbar Alignment", taskbarAlignmentTweak!.Name);
        Assert.Equal("Display File Icons On Thumbnails", typeOverlayTweak!.Name);
        Assert.Equal("Automatic Restart on System Failure", bsodAutoRebootTweak!.Name);
        Assert.Equal("Display Blue Screen Parameters", bsodDisplayParametersTweak!.Name);
        Assert.Equal("Fullscreen Optimizations", disableFullscreenOptimizationsTweak!.Name);
        Assert.Equal("Windows Game Recording and Broadcasting", disableGameRecordingBroadcastingTweak!.Name);
        Assert.Equal("Remote Windows Search Queries", disableSearchRemoteQueriesTweak!.Name);
        Assert.Equal("Web Results in Windows Search", disableSearchWebResultsTweak!.Name);
        Assert.Equal("Indexing of Encrypted Files", enableIndexingEncryptedItemsTweak!.Name);
        Assert.Equal("Graphics TDR DDI Delay", graphicsTdrDdiDelayTweak!.Name);
        Assert.Equal("Graphics TDR Delay", graphicsTdrDelayTweak!.Name);
        Assert.Equal("Graphics TDR Level", graphicsTdrLevelTweak!.Name);
        Assert.Equal("DWM Overlay Minimum FPS Check", dwmDisableOverlayMinFpsTweak!.Name);
        Assert.Equal("Graphics TDR Limit Count", graphicsTdrLimitCountTweak!.Name);
        Assert.Equal("Graphics TDR Limit Time", graphicsTdrLimitTimeTweak!.Name);
        Assert.Equal("Threaded DPCs", kernelThreadDpcEnableTweak!.Name);
        Assert.Equal("Clear Page File at Shutdown", memoryClearPagefileAtShutdownTweak!.Name);
        Assert.Equal("Disable Paging Executive", memoryDisablePagingExecutiveTweak!.Name);
        Assert.Equal("Large System Cache", memoryLargeSystemCacheClientTweak!.Name);
        Assert.Equal("Nonpaged Pool Size", memoryNonpagedPoolDynamicTweak!.Name);
        Assert.Equal("Paged Pool Size", memoryPagedPoolDynamicTweak!.Name);
        Assert.Equal("Registry Size Limit / Registry Quota", memoryRegistryQuotaDefaultTweak!.Name);
        Assert.Equal("NTFS 8.3 Short Name Creation", ntfsDisable8dot3Tweak!.Name);
        Assert.Equal("NTFS Last Access Time Updates", ntfsDisableLastAccessTweak!.Name);
        Assert.Equal("Win32 Long Paths", ntfsEnableLongPathsTweak!.Name);
        Assert.Equal("NTFS Memory Usage", ntfsResetMemoryUsageTweak!.Name);
        Assert.Equal("NTFS MFT Zone Reservation", ntfsResetMftZoneTweak!.Name);
        Assert.Equal("Service Shutdown Timeout", waitToKillServiceTimeoutTweak!.Name);
        Assert.Equal("Foreground Scheduling Priority / Win32PrioritySeparation", priorityControlTweak!.Name);
        Assert.Equal("Reliability Event Timestamping", reliabilityTimestampEnabledTweak!.Name);
        Assert.Equal("Disable Window Animations", disableAnimationsTweak!.Name);
        Assert.Equal("Remove Menu Show Delay", disableMenuShowDelayTweak!.Name);
        Assert.Equal("Acrylic Blur on the Logon Background", disableAcrylicLogonTweak!.Name);
        Assert.Equal("Common Control and Window Animations", disableCommonControlAnimationsTweak!.Name);
        Assert.Equal("First Sign-In Animation", disableFirstSigninAnimationTweak!.Name);
        Assert.Equal("Lock Screen Camera Access", disableLockScreenCameraTweak!.Name);
        Assert.Equal("Changing the Lock Screen and Logon Image", disableLockScreenChangesTweak!.Name);
        Assert.Equal("Automatic App Archiving", disableAppArchivingTweak!.Name);
        Assert.Equal("Automatic Maintenance", disableAutoMaintenanceTweak!.Name);
        Assert.Equal("Background Group Policy Refresh", disableBackgroundGpUpdatesTweak!.Name);
        Assert.Equal("Clipboard History and Cross-Device Clipboard Sync", disableClipboardHistoryTweak!.Name);
        Assert.Equal("RDP Clipboard Redirection", disableClipboardRedirectionTweak!.Name);
        Assert.Equal("Aero Shake Window Minimizing Gesture", aeroShakeTweak!.Name);
        Assert.Equal("Wallpaper JPEG Import Quality", disableJpegReductionTweak!.Name);
        Assert.Equal("Search Highlights", disableSearchHighlightsPolicyTweak!.Name);
        Assert.Equal("Startup Program Delay", disableStartupDelayTweak!.Name);
        Assert.Equal("Game Mode", enableGameModeTweak!.Name);
        Assert.IsType<RegistryValuePresetBatchTweak>(beepTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(blockMicrosoftAccountsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(biometricsDomainLogonTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(biometricsLogonTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(biometricsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(cameraTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(consumerAccountContentTweak);
        Assert.IsType<RegistryValueTweak>(developerModeTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableAdvertisingIdTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(dotnetTelemetryTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableAppDiagnosticsTweak);
        Assert.IsType<RegistryValueTweak>(disableAppLaunchTrackingTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableAppSuggestionsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableApplicationTelemetryTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableBackgroundAppsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableCopilotTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableCrossDeviceExperiencesPolicyTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableDeviceNameTelemetryTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableDiagnosticDataDeleteTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableDiagnosticDataViewerTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableFeedbackNotificationsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableFindMyDeviceTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableFontProvidersTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(fullPathTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(hiddenAudioTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disconnectedAudioTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(compactModeTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(compressedColorTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableChatTweak);
        Assert.IsType<RegistryValueTweak>(disableLowDiskSpaceWarningTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableActiveProbingTweak);
        Assert.IsType<RegistryValueTweak>(disableFeedbackFrequencyTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableIpv6Tweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableLockScreenTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableLlmnrTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(enableLltdIoTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableLocalSecurityQuestionsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableLocationScriptingTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableLocationServicesTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableMdmEnrollmentTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableMdnsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableMessageSyncTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disablePlaintextSmbPasswordsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableFileHistoryTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableLanguageListAccessTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableLocationConsentSystemTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableOneSettingsDownloadsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableOnlineTipsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disablePcaDiagnosticsPolicyTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableProgramCompatibilityAssistantTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disablePhoneLinkingTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableRecallTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableResumeTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableRsopLoggingTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableSearchBoxSuggestionsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableSearchHistoryTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableSensorsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableSmb1Tweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableSmb2Tweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableStepsRecorderTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableWifiSenseTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableWindowsLocationProviderTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(enableLltdResponderTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableMirroringTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableNetbiosResolutionTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(requireNtlmSspClientSessionSecurityTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(smbEnableLargeMtuTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(smbEncryptDataTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(smbRejectUnencryptedAccessTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableSmartNameResolutionTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableTelemetryChangeNotificationsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableTelemetryOptInUiTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableTileTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableToastTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableSwitchbackPolicyTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(hideLastLoggedInUserTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(hideRecommendedPersonalizedSitesPolicyTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(hideRecommendedPersonalizedSitesUserTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(hideRecommendedSectionPolicyTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(hideRecommendedSectionUserTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(hideUsernameAtSigninTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(limitDiagnosticLogCollectionTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(limitDumpCollectionTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(troubleshooterDontRunTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableWindowsTipsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(driveLettersTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(hiddenFilesTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(fileExtensionsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(infoTipsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(launchSeparateProcessTweak);
        Assert.IsType<RegistryValueTweak>(longPathsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(policyTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(preferIpv4Tweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(powershellExecutionTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(pythonPathFixTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(showProtectedFilesTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(statusBarTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(taskbarAlignmentTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(typeOverlayTweak);
        Assert.IsType<RegistryValueBatchTweak>(watchdogTweak);
        Assert.IsType<RegistrySubtreeTweak>(subtreeTweak);
        Assert.IsType<RegistryValueBatchTweak>(executiveTweak);
        Assert.IsType<RegistryValueTweak>(kernelTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(bsodAutoRebootTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(bsodDisplayParametersTweak);
        Assert.IsType<RegistryValueBatchTweak>(disableFullscreenOptimizationsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableGameRecordingBroadcastingTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableSearchRemoteQueriesTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableSearchWebResultsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(enableIndexingEncryptedItemsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(graphicsTdrDdiDelayTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(graphicsTdrDelayTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(graphicsTdrLevelTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(dwmDisableOverlayMinFpsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(graphicsTdrLimitCountTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(graphicsTdrLimitTimeTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(kernelThreadDpcEnableTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(memoryClearPagefileAtShutdownTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(memoryDisablePagingExecutiveTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(memoryLargeSystemCacheClientTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(memoryNonpagedPoolDynamicTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(memoryPagedPoolDynamicTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(memoryRegistryQuotaDefaultTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(ntfsDisable8dot3Tweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(ntfsDisableLastAccessTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(ntfsEnableLongPathsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(ntfsResetMemoryUsageTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(ntfsResetMftZoneTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(waitToKillServiceTimeoutTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(priorityControlTweak);
        Assert.IsType<RegistryValueBatchTweak>(reliabilityTimestampEnabledTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableAnimationsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableMenuShowDelayTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableAcrylicLogonTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableCommonControlAnimationsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableFirstSigninAnimationTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableLockScreenCameraTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableLockScreenChangesTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableAppArchivingTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableAutoMaintenanceTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableBackgroundGpUpdatesTweak);
        Assert.IsType<RegistryValueBatchTweak>(disableClipboardHistoryTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableClipboardRedirectionTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(aeroShakeTweak);
        Assert.IsType<RegistryValueTweak>(disableJpegReductionTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableSearchHighlightsPolicyTweak);
        Assert.IsType<RegistryValueTweak>(disableStartupDelayTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(enableGameModeTweak);
    }
}
