using RegProbe.Application.Services;
using RegProbe.Engine.Tweaks;

namespace RegProbe.Tests;

public sealed class ResearchAppSurfaceCatalogTests
{
    [Fact]
    public void Catalog_Surfaces_Validated_Research_Cards_From_App_Surface_Manifest()
    {
        var catalog = new TweakCatalogService();

        var beepTweak = catalog.FindById("audio.disable-beep");
        var blockMicrosoftAccountsTweak = catalog.FindById("privacy.block-microsoft-accounts");
        var developerModeTweak = catalog.FindById("developer.windows-dev-mode");
        var disableAdvertisingIdTweak = catalog.FindById("privacy.disable-advertising-id");
        var dotnetTelemetryTweak = catalog.FindById("developer.dotnet-telemetry-disable");
        var disableAppDiagnosticsTweak = catalog.FindById("privacy.disable-app-diagnostics");
        var disableAppLaunchTrackingTweak = catalog.FindById("privacy.disable-app-launch-tracking");
        var disableApplicationTelemetryTweak = catalog.FindById("privacy.disable-application-telemetry");
        var disableBackgroundAppsTweak = catalog.FindById("privacy.disable-background-apps");
        var fullPathTweak = catalog.FindById("explorer.show-full-path");
        var policyTweak = catalog.FindById("policy.system.enable-virtualization");
        var disconnectedAudioTweak = catalog.FindById("audio.show-disconnected-devices");
        var hiddenAudioTweak = catalog.FindById("audio.show-hidden-devices");
        var compactModeTweak = catalog.FindById("explorer.enable-explorer-compact-mode");
        var compressedColorTweak = catalog.FindById("explorer.show-compressed-and-encrypted-files-in-color");
        var disableChatTweak = catalog.FindById("explorer.disable-taskbar-chat");
        var disableLowDiskSpaceWarningTweak = catalog.FindById("explorer.disable-low-disk-space-warning");
        var disableActiveProbingTweak = catalog.FindById("network.disable-active-probing");
        var disableFeedbackFrequencyTweak = catalog.FindById("notifications.disable-feedback-frequency");
        var disableIpv6Tweak = catalog.FindById("network.disable-ipv6");
        var disableLockScreenTweak = catalog.FindById("notifications.disable-lock-screen");
        var disableLlmnrTweak = catalog.FindById("network.disable-llmnr");
        var disableMdnsTweak = catalog.FindById("network.disable-mdns");
        var disableMirroringTweak = catalog.FindById("notifications.disable-mirroring");
        var disableNetbiosResolutionTweak = catalog.FindById("network.disable-netbios-resolution");
        var disableSmartNameResolutionTweak = catalog.FindById("network.disable-smart-name-resolution");
        var disableTileTweak = catalog.FindById("notifications.disable-tile");
        var disableToastTweak = catalog.FindById("notifications.disable-toast");
        var driveLettersTweak = catalog.FindById("explorer.show-drive-letters-first");
        var infoTipsTweak = catalog.FindById("explorer.show-info-tips");
        var launchSeparateProcessTweak = catalog.FindById("explorer.launch-folder-windows-in-a-separate-process");
        var longPathsTweak = catalog.FindById("developer.enable-windows-long-paths");
        var hiddenFilesTweak = catalog.FindById("explorer.show-hidden-files");
        var fileExtensionsTweak = catalog.FindById("explorer.show-file-extensions");
        var preferIpv4Tweak = catalog.FindById("network.prefer-ipv4");
        var powershellExecutionTweak = catalog.FindById("developer.powershell-execution");
        var pythonPathFixTweak = catalog.FindById("developer.python-path-fix");
        var showProtectedFilesTweak = catalog.FindById("explorer.show-protected-operating-system-files");
        var statusBarTweak = catalog.FindById("explorer.show-status-bar");
        var taskbarAlignmentTweak = catalog.FindById("explorer.taskbar-alignment-left");
        var typeOverlayTweak = catalog.FindById("explorer.show-type-overlay");
        var powerTweak = catalog.FindById("power.control.class1-initial-unpark-count");
        var watchdogTweak = catalog.FindById("power.session-watchdog-timeouts");
        var subtreeTweak = catalog.FindById("power.control.power-request-override-subtree");
        var executiveTweak = catalog.FindById("system.executive-additional-worker-threads");
        var kernelTweak = catalog.FindById("system.kernel.disable-exception-chain-validation");

        Assert.NotNull(beepTweak);
        Assert.NotNull(blockMicrosoftAccountsTweak);
        Assert.NotNull(developerModeTweak);
        Assert.NotNull(disableAdvertisingIdTweak);
        Assert.NotNull(dotnetTelemetryTweak);
        Assert.NotNull(disableAppDiagnosticsTweak);
        Assert.NotNull(disableAppLaunchTrackingTweak);
        Assert.NotNull(disableApplicationTelemetryTweak);
        Assert.NotNull(disableBackgroundAppsTweak);
        Assert.NotNull(fullPathTweak);
        Assert.NotNull(hiddenAudioTweak);
        Assert.NotNull(disconnectedAudioTweak);
        Assert.NotNull(compactModeTweak);
        Assert.NotNull(compressedColorTweak);
        Assert.NotNull(disableChatTweak);
        Assert.NotNull(disableLowDiskSpaceWarningTweak);
        Assert.NotNull(disableActiveProbingTweak);
        Assert.NotNull(disableFeedbackFrequencyTweak);
        Assert.NotNull(disableIpv6Tweak);
        Assert.NotNull(disableLockScreenTweak);
        Assert.NotNull(disableLlmnrTweak);
        Assert.NotNull(disableMdnsTweak);
        Assert.NotNull(disableMirroringTweak);
        Assert.NotNull(disableNetbiosResolutionTweak);
        Assert.NotNull(disableSmartNameResolutionTweak);
        Assert.NotNull(disableTileTweak);
        Assert.NotNull(disableToastTweak);
        Assert.NotNull(driveLettersTweak);
        Assert.NotNull(hiddenFilesTweak);
        Assert.NotNull(fileExtensionsTweak);
        Assert.NotNull(infoTipsTweak);
        Assert.NotNull(launchSeparateProcessTweak);
        Assert.NotNull(longPathsTweak);
        Assert.NotNull(policyTweak);
        Assert.NotNull(preferIpv4Tweak);
        Assert.NotNull(powershellExecutionTweak);
        Assert.NotNull(pythonPathFixTweak);
        Assert.NotNull(showProtectedFilesTweak);
        Assert.NotNull(powerTweak);
        Assert.NotNull(statusBarTweak);
        Assert.NotNull(taskbarAlignmentTweak);
        Assert.NotNull(watchdogTweak);
        Assert.NotNull(subtreeTweak);
        Assert.NotNull(executiveTweak);
        Assert.NotNull(kernelTweak);
        Assert.NotNull(typeOverlayTweak);
        Assert.Equal("System Beep Driver", beepTweak!.Name);
        Assert.Equal("Microsoft Accounts on This Device", blockMicrosoftAccountsTweak!.Name);
        Assert.Equal("Windows Developer Mode", developerModeTweak!.Name);
        Assert.Equal("Disable Advertising ID", disableAdvertisingIdTweak!.Name);
        Assert.Equal(".NET CLI Telemetry Opt-Out", dotnetTelemetryTweak!.Name);
        Assert.Equal("App Diagnostic Information Access", disableAppDiagnosticsTweak!.Name);
        Assert.Equal("App Launch Tracking", disableAppLaunchTrackingTweak!.Name);
        Assert.Equal("Disable Application Telemetry", disableApplicationTelemetryTweak!.Name);
        Assert.Equal("Background App Execution", disableBackgroundAppsTweak!.Name);
        Assert.Equal("Show Full Path in Explorer", fullPathTweak!.Name);
        Assert.Equal("Show Hidden Audio Devices", hiddenAudioTweak!.Name);
        Assert.Equal("Show Disconnected Audio Devices", disconnectedAudioTweak!.Name);
        Assert.Equal("Enable Explorer Compact View", compactModeTweak!.Name);
        Assert.Equal("Show Compressed and Encrypted Files in Color", compressedColorTweak!.Name);
        Assert.Equal("Taskbar Chat Icon", disableChatTweak!.Name);
        Assert.Equal("Low Disk Space Warning", disableLowDiskSpaceWarningTweak!.Name);
        Assert.Equal("NCSI Active Probing Policy", disableActiveProbingTweak!.Name);
        Assert.Equal("Windows Feedback Request Frequency", disableFeedbackFrequencyTweak!.Name);
        Assert.Equal("IPv6 Stack Disable Override", disableIpv6Tweak!.Name);
        Assert.Equal("Lock Screen Toast Notifications", disableLockScreenTweak!.Name);
        Assert.Equal("Link-Local Multicast Name Resolution (LLMNR)", disableLlmnrTweak!.Name);
        Assert.Equal("Set mDNS Policy to Local Settings", disableMdnsTweak!.Name);
        Assert.Equal("Notification Mirroring", disableMirroringTweak!.Name);
        Assert.Equal("DNS Client NetBIOS Name Resolution", disableNetbiosResolutionTweak!.Name);
        Assert.Equal("Smart Multi-Homed Name Resolution", disableSmartNameResolutionTweak!.Name);
        Assert.Equal("Tile Notifications", disableTileTweak!.Name);
        Assert.Equal("Toast Notifications", disableToastTweak!.Name);
        Assert.Equal("Show Drive Letters First", driveLettersTweak!.Name);
        Assert.Equal("Show Hidden Files and Folders", hiddenFilesTweak!.Name);
        Assert.Equal("Show File Extensions", fileExtensionsTweak!.Name);
        Assert.Equal("Show Explorer Info Tips", infoTipsTweak!.Name);
        Assert.Equal("Launch Folder Windows in a Separate Process", launchSeparateProcessTweak!.Name);
        Assert.Equal("Windows Long Paths", longPathsTweak!.Name);
        Assert.Equal("Enable Virtualization", policyTweak!.Name);
        Assert.Equal("IPv4 Preference Override", preferIpv4Tweak!.Name);
        Assert.Equal("PowerShell Script Execution Policy", powershellExecutionTweak!.Name);
        Assert.Equal("Enable Windows Long Paths for Python Workflows", pythonPathFixTweak!.Name);
        Assert.Equal("Show Protected Operating System Files", showProtectedFilesTweak!.Name);
        Assert.Equal("Class1 Initial Unpark Count", powerTweak!.Name);
        Assert.Equal("Show Status Bar", statusBarTweak!.Name);
        Assert.Equal("Taskbar Alignment", taskbarAlignmentTweak!.Name);
        Assert.Equal("Display File Icons On Thumbnails", typeOverlayTweak!.Name);
        Assert.IsType<RegistryValuePresetBatchTweak>(beepTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(blockMicrosoftAccountsTweak);
        Assert.IsType<RegistryValueTweak>(developerModeTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableAdvertisingIdTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(dotnetTelemetryTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableAppDiagnosticsTweak);
        Assert.IsType<RegistryValueTweak>(disableAppLaunchTrackingTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableApplicationTelemetryTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableBackgroundAppsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(fullPathTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(hiddenAudioTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disconnectedAudioTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(compactModeTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(compressedColorTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableChatTweak);
        Assert.IsType<RegistryValueTweak>(disableLowDiskSpaceWarningTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableActiveProbingTweak);
        Assert.IsType<RegistryValueTweak>(disableFeedbackFrequencyTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableIpv6Tweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableLockScreenTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableLlmnrTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableMdnsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableMirroringTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableNetbiosResolutionTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableSmartNameResolutionTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableTileTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(disableToastTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(driveLettersTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(hiddenFilesTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(fileExtensionsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(infoTipsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(launchSeparateProcessTweak);
        Assert.IsType<RegistryValueTweak>(longPathsTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(policyTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(preferIpv4Tweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(powershellExecutionTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(pythonPathFixTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(showProtectedFilesTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(statusBarTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(taskbarAlignmentTweak);
        Assert.IsType<RegistryValuePresetBatchTweak>(typeOverlayTweak);
        Assert.IsType<RegistryValueBatchTweak>(watchdogTweak);
        Assert.IsType<RegistrySubtreeTweak>(subtreeTweak);
        Assert.IsType<RegistryValueBatchTweak>(executiveTweak);
        Assert.IsType<RegistryValueTweak>(kernelTweak);
    }
}
