<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>RegProbe.CLI</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>RegProbe.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.7" />
    <PackageReference Include="System.Management" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\\application\\application.csproj" />
    <ProjectReference Include="..\\core\\core.csproj" />
    <ProjectReference Include="..\\engine\\engine.csproj" />
    <ProjectReference Include="..\\infrastructure\\infrastructure.csproj" />
  </ItemGroup>

</Project>
