#!/usr/bin/env python3
from __future__ import annotations

import csv
import html
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
CATALOG_CSV = REPO_ROOT / "Docs" / "tweaks" / "tweak-catalog.csv"
OUTPUT_HTML = REPO_ROOT / "Docs" / "tweaks" / "tweak-details.html"


def load_entries() -> list[dict[str, str]]:
    if not CATALOG_CSV.exists():
        raise FileNotFoundError(f"Missing catalog: {CATALOG_CSV}")

    entries: list[dict[str, str]] = []
    with CATALOG_CSV.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            entries.append({
                "id": (row.get("id") or "").strip(),
                "name": (row.get("name") or "").strip(),
                "description": (row.get("description") or "").strip(),
                "risk": (row.get("risk") or "").strip(),
                "category": (row.get("category") or "").strip(),
                "area": (row.get("area") or "").strip(),
                "source": (row.get("source") or "").strip(),
                "docs": (row.get("docs") or "").strip(),
            })
    return [entry for entry in entries if entry["id"]]


def rel_path_from_docs(path: str) -> str:
    if not path:
        return ""
    path = path.replace("\\", "/")
    if path.startswith("Docs/"):
        return "../" + path[len("Docs/") :]
    return path


def build_html(entries: list[dict[str, str]]) -> str:
    lines = [
        "<!doctype html>",
        "<html lang=\"en\">",
        "<head>",
        "  <meta charset=\"utf-8\">",
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
        "  <title>Tweak Details</title>",
        "  <style>",
        "    body { font-family: Segoe UI, Arial, sans-serif; background: #f6f7fb; color: #1f2430; }",
        "    .container { max-width: 1100px; margin: 24px auto; padding: 0 16px; }",
        "    h1 { font-size: 22px; margin: 0 0 6px; }",
        "    .note { color: #54606f; margin-bottom: 18px; font-size: 13px; }",
        "    .entry { background: #fff; border-radius: 10px; padding: 14px 16px; margin-bottom: 12px; box-shadow: 0 1px 4px rgba(0,0,0,0.04); }",
        "    .entry h2 { font-size: 16px; margin: 0 0 6px; }",
        "    .meta { display: grid; grid-template-columns: 120px 1fr; gap: 6px 12px; font-size: 13px; }",
        "    .label { color: #4c566a; font-weight: 600; }",
        "    code { font-family: Consolas, monospace; font-size: 12px; }",
        "    a { color: #2f6f9b; text-decoration: none; }",
        "    a:hover { text-decoration: underline; }",
        "  </style>",
        "</head>",
        "<body>",
        "  <div class=\"container\">",
        "    <h1>Tweak Details</h1>",
        "    <div class=\"note\">Generated from Docs/tweaks/tweak-catalog.csv. Do not edit this file manually.</div>",
    ]

    for entry in entries:
        tweak_id = html.escape(entry["id"])
        name = html.escape(entry["name"] or tweak_id)
        category = html.escape(entry["category"] or "Other")
        area = html.escape(entry["area"] or "Other")
        risk = html.escape(entry["risk"] or "Unknown")
        description = html.escape(entry["description"] or "No description provided.")
        source = html.escape(entry["source"] or "Unknown")
        docs = entry["docs"]
        main_doc = rel_path_from_docs(docs)
        main_doc_label = html.escape(docs or "Docs/tweaks/tweaks.md")

        lines.extend([
            f"    <div class=\"entry\" id=\"{tweak_id}\">",
            f"      <h2><code>{tweak_id}</code> - {name}</h2>",
            "      <div class=\"meta\">",
            f"        <div class=\"label\">Changes</div><div>{description}</div>",
            f"        <div class=\"label\">Risk</div><div>{risk}</div>",
            f"        <div class=\"label\">Category</div><div>{category}</div>",
            f"        <div class=\"label\">Area</div><div>{area}</div>",
            f"        <div class=\"label\">Source</div><div><code>{source}</code></div>",
        ])

        if main_doc:
            main_doc_url = f"{main_doc}#{entry['id']}" if entry["id"] else main_doc
            lines.append(
                f"        <div class=\"label\">Main doc</div>"
                f"<div><a href=\"{html.escape(main_doc_url)}\">{main_doc_label}</a></div>"
            )
        else:
            lines.append(
                "        <div class=\"label\">Main doc</div>"
                "<div><code>Docs/tweaks/tweaks.md</code></div>"
            )

        lines.extend([
            "      </div>",
            "    </div>",
        ])

    lines.extend([
        "  </div>",
        "</body>",
        "</html>",
    ])
    return "\n".join(lines) + "\n"


def main() -> int:
    entries = load_entries()
    OUTPUT_HTML.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_HTML.write_text(build_html(entries), encoding="utf-8")
    print(f"Wrote {OUTPUT_HTML} with {len(entries)} entries.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
